### ISSUE TITLE
Maldegem BC is defined twice in club.csv and this blocks the DB load

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Badminton-PBO/lion-freaky#37]
```
Discovered by Ronny + communicated to Ruben.

```

Original issue reported on code.google.com by `thomas.d...@gmail.com` on 21 Jan 2015 at 5:02

**Comment by ThomasDekeyser** [comment]
In recent dumps of clubs.csv, Maldegem BC is only mentioned once.
