### ISSUE TITLE
Als ploegkapitein wil ik ook spelers kunnen opstellen die zowel als Jeugd en als Competitiespeler staan ingeschreven

### ISSUE THREAD

**Issue by CnuddeGlenn** [Badminton-PBO/lion-freaky#40]
Mail gekregen van Vladbad 1G, deze spelers zouden in de database zitten.

- Felien Botte
- Sarah Wandels
- Eloïme Bossuwe
- Max Dierickx
- Simon Krols
- Tim Krols
- Niels Desmet
- Arne Lepez
- Daan Krols

Groeten,
Glenn

**Comment by CnuddeGlenn** [comment]
Dit al bekeken? 

Groeten,
Glenn

**Comment by ThomasDekeyser** [comment]
Jeugdspelers die momenteel niet in DB worden opgeladen. 
Q1: Zitten ze in de CSV?

**Comment by ThomasDekeyser** [comment]
Probleem analyse
In players.csv komen Jeugd spelers verschillende malen in voor. Momenteel is het zo als er dubbels zijn er enkel de speler met role "Uitgeleende speler" overgehouden wordt. Indien een speler dus Jeugd& competitie was maar NIET "Uitgeleend speler" dan werden alle entries voor de speler verwijderd waardoor die speler niet langer bestond.

bv. Felien
35B9F04A-EEA3-4306-AB02-437E795BEC40;BC VLA-BAD;D60FFEAD-3B74-476A-A26F-DC16D26117C2;50109432;BOTTE;;;Felien;Pontweg 73;;;9890;Asper;;BEL;V;28-8-2000;09/384.11.59;02/577.57.75;;;;patrick.botte1@telenet.be;http://SELECTIE.GROEP;;13-9-2010;31-12-9999;Speler;C2;D;D;Competitiespeler
35B9F04A-EEA3-4306-AB02-437E795BEC40;BC VLA-BAD;D60FFEAD-3B74-476A-A26F-DC16D26117C2;50109432;BOTTE;;;Felien;Pontweg 73;;;9890;Asper;;BEL;V;28-8-2000;09/384.11.59;02/577.57.75;;;;patrick.botte1@telenet.be;http://SELECTIE.GROEP;;1-1-2013;31-12-9999;KYU speler rood;C2;D;D;Jeugd
35B9F04A-EEA3-4306-AB02-437E795BEC40;BC VLA-BAD;D60FFEAD-3B74-476A-A26F-DC16D26117C2;50109432;BOTTE;;;Felien;Pontweg 73;;;9890;Asper;;BEL;V;28-8-2000;09/384.11.59;02/577.57.75;;;;patrick.botte1@telenet.be;http://SELECTIE.GROEP;;1-1-2013;31-12-9999;KYU speler rood;C2;D;D;Jeugd
35B9F04A-EEA3-4306-AB02-437E795BEC40;BC VLA-BAD;D60FFEAD-3B74-476A-A26F-DC16D26117C2;50109432;BOTTE;;;Felien;Pontweg 73;;;9890;Asper;;BEL;V;28-8-2000;09/384.11.59;02/577.57.75;;;;patrick.botte1@telenet.be;http://SELECTIE.GROEP;;1-1-2013;31-12-9999;KYU speler wit;C2;D;D;Jeugd

**Comment by ThomasDekeyser** [comment]
![gh-40_testresult](https://cloud.githubusercontent.com/assets/10930784/7337071/2f535968-ec1b-11e4-9b8c-9c4f3056c037.png)
