### ISSUE TITLE
Als ploegkapitein wil ik spelers gelijkaardig aan hoogste klassement kunnen opstellen conform VBL interpretatie van C320 ART53.2. Momenteel wordt gekeken naar som van individuele indexes

### ISSUE THREAD

**Issue by CnuddeGlenn** [Badminton-PBO/lion-freaky#43]
Beste,

Er is een fout bij het opstellen van spelers met een hogere index dan de basis spelers ook al is deze gerechtigd te spelen.

Bv. Speler 1 heeft 10 punten B2/C1
      Speler 2 heeft 10 punten C1/B2
      Speler 3 heeft 10 punten B2/C1
      Speler 4 heeft   8 punten C1/C1

Max index 38.

Opstelling: Speler 1: 12 B2/B2
                  Speler 2: 10 B2/C1
                  Speler 3:  8 C1/C1
                  Speler 3:  8 C1/C1

Max index 38.

Deze index en opstelling is geldig. Kunnen jullie hiervoor zorgen? Momenteel staat speler 1 dan bij niet opstelbare spelers maar dit klopt niet.

Groeten,
Glenn

**Comment by ThomasDekeyser** [comment]
Testclub-daat wat aangepast om dit te kunnen reproduceren & fixen
Man5: enkel=B2, dubbel=C1, in basisteam 3H
Man19: enkel=B2,dubbel=B2 niet in basisteams
