### ISSUE TITLE
Als ik een wedstrijd bevestigd heb verdwijnt het groene  balkje te rap.

### ISSUE THREAD

**Issue by stijncab** [Badminton-PBO/lion-freaky#45]
Sarah had te weinig tijd om dit te lezen. Ze stelt voor om dit te laten verdwijnen als je op iets klikt of misschein zelf niet te laten verdwijnen

**Comment by stijncab** [comment]
Veel beter ;)
Muggeziftstijn

-----Oorspronkelijk bericht-----
Van: "ThomasDekeyser" <notifications@github.com>
Verzonden: ‎23/‎06/‎2015 0:02
Aan: "Badminton-PBO/lion-freaky" <lion-freaky@noreply.github.com>
CC: "stijncab" <stijncabus@gmail.com>
Onderwerp: Re: [lion-freaky] Als ik een wedstrijd bevestigd heb verdwijnt hetgroene  balkje te rap. (#45)

Closed #45 via 81fe5fd.

**Comment by ThomasDekeyser** [comment]
Timeout stond op 6 sec. Verhoogd naar 10 sec.
Op iets anders klikken dat het verdwijnt blijkt vrij lastig te zijn. Tenzij je natuurlijk telkens expliciet wil verplichten oom weg te klikken -> maar dat lijkt me geen goede oplossing.
