### ISSUE TITLE
Als betrokken ploegkapitein wil ik een bevestigingsmail ontvangen als PBO uiteindelijk match op de toernooi.nl heeft aangepast.

### ISSUE THREAD

**Issue by stijncab** [Badminton-PBO/lion-freaky#46]
zelf maar half overtuigd maar er zullen wel controlefreaks zijn die dit verwachten

**Comment by ThomasDekeyser** [comment]
Had ik ook aan gedacht maar als nice2have op todo-list gezet

**Comment by ThomasDekeyser** [comment]
Example in lionfreaky@yahoo.com
Subject : Verplaatsings aanvraag Gentse 1H - Wit-Wit 2H verwerkt 
Body : De wedstrijd "Gentse 1H - Wit-Wit 2H" is verplaatst op toernooi.nl naar "zaterdag 25 oktober, 10:00"
