### ISSUE TITLE
video's tutorial

### ISSUE THREAD

**Issue by stijncab** [Badminton-PBO/lion-freaky#47]
Hey ,nog wat kleine aanpassingen nodig, maar graag toch al wat feedback:
https://youtu.be/i0MNquAJZEY
https://www.youtube.com/watch?v=GCQUNj13kPo

**Comment by ThomasDekeyser** [comment]
Kan je ook niet vergeten de titel in youtube te wijzigen
"bandicam 2015 06 30 23 51 56 716" is nogal nietszeggend

**Comment by ThomasDekeyser** [comment]
Bestaande filmpjes toegevoegd:
Home scherm via foto
Login scherm via "?" button
Verplaatsings module zelf via "?" button
